using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Marine.Customization.Gui;

[GenerateTypedNameReferences]
public sealed partial class MCCustomizationSelectBuiWindow : DefaultWindow
{
    public MCCustomizationSelectBuiWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
