using Content.Client._MC.ASRS.UI.Buttons;
using Content.Shared._MC.ASRS.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Views;

[GenerateTypedNameReferences]
public sealed partial class MCASRSOrdersView : MCASRSView
{
    public event Action<MCASRSEntry, int>? OrderCountChanged;

    public MCASRSOrdersView()
    {
        RobustXamlLoader.Load(this);
    }

    public override void Open(MCASRSBui bui)
    {
        base.Open(bui);

        CategoryNameLabel.SetMessage(Loc.GetString(bui.Category.Name));

        Container.Children.Clear();
        foreach (var entry in bui.Category.Entries)
        {
            Container.Children.Add(new MCASRSOrderButton(entry, bui.Store.GetValueOrDefault(entry), OnCountChanged, bui.SettingShowIcons));
        }
    }

    private void OnCountChanged(MCASRSEntry entry, int count)
    {
        OrderCountChanged?.Invoke(entry, count);
    }
}
