using Content.Client._MC.ASRS.UI.Buttons;
using Content.Shared._MC.ASRS.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Views;

[GenerateTypedNameReferences]
public sealed partial class MCASRSOrdersView : MCASRSView
{
    public event Action<MCASRSEntry, int>? OrderCountChanged;

    private MCASRSBui? _bui;

    public MCASRSOrdersView()
    {
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += _ => Refresh();
    }

    public override void Open(MCASRSBui bui)
    {
        base.Open(bui);

        _bui = bui;

        CategoryNameLabel.SetMessage(Loc.GetString(bui.Category.Name));

        SearchBar.Text = string.Empty;

        Refresh();
    }

    private void Refresh()
    {
        if (_bui == null)
            return;

        Container.Children.Clear();
        var searchText = SearchBar.Text?.ToLowerInvariant() ?? string.Empty;

        foreach (var entry in _bui.Category.Entries)
        {
            if (!string.IsNullOrEmpty(searchText))
            {
                var name = entry.Name;

                if (string.IsNullOrEmpty(name) && entry.Entities.Count > 0)
                {
                    var locManager = IoCManager.Resolve<ILocalizationManager>();
                    if (locManager.GetEntityData(entry.Entities[0]).Name is { } entityName)
                        name = entityName;
                }

                if (name is null || !Loc.GetString(name).Contains(searchText, StringComparison.InvariantCultureIgnoreCase))
                    continue;
            }

            Container.Children.Add(new MCASRSOrderButton(entry, _bui.Store.GetValueOrDefault(entry), OnCountChanged, _bui.SettingShowIcons));
        }
    }

    private void OnCountChanged(MCASRSEntry entry, int count)
    {
        OrderCountChanged?.Invoke(entry, count);
    }
}
