using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Bomb.UI;

[GenerateTypedNameReferences]
public sealed partial class MCBombPasswordWindow : DefaultWindow
{
    public MCBombPasswordWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetDisplay(string text)
    {
        DisplayLabel.Text = text;
    }
}
