- type: entity
  parent: MCClothing
  id: MCClothingShoes
  abstract: true
  components:
  - type: Clothing
    slots: [ FEET ]
  - type: Sprite
    state: icon
  - type: Item
    size: Normal
  - type: ProtectedFromStepTriggers
