using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client._MC.Xeno.Hive.UI;

[GenerateTypedNameReferences]
public sealed partial class MCXenoHiveStatusWindow : DefaultWindow
{
    public MCXenoHiveStatusWindow()
    {
    }
}
