using System.Linq;
using System.Numerics;
using Content.Shared._MC.Xeno.Hive.Prototypes;
using Content.Shared._MC.Xeno.Hive.UI.Status;
using Content.Shared._RMC14.TacticalMap;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._MC.Xeno.Hive.UI;

[GenerateTypedNameReferences]
public sealed partial class MCXenoHiveStatusWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entity = null!;
    [Dependency] private readonly IPrototypeManager _prototype = null!;

    public event Action? OnButtonSkins;
    public event Action? OnButtonBlessings;
    public event Action? OnButtonEvolve;
    public event Action? OnButtonDevolve;
    public event Action<NetEntity>? OnButtonWatch;

    private readonly SpriteSystem _sprite;

    public MCXenoHiveStatusWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        // Subscribe to button events exactly once in the constructor
        // to avoid memory leaks and duplicate invocations during state updates.
        SkinsButton.OnPressed += _ => OnButtonSkins?.Invoke();
        BlessingsButton.OnPressed += _ => OnButtonBlessings?.Invoke();
        EvolveButton.OnPressed += _ => OnButtonEvolve?.Invoke();
        DevolveButton.OnPressed += _ => OnButtonDevolve?.Invoke();
    }

    /// <summary>
    /// Main method for updating the window state.
    /// </summary>
    public void SetState(MCXenoHiveStatusXenosBuiState state)
    {
        UpdateButtonsState(state);
        UpdateHeaderInfo(state);
        UpdateEvolution(state);
        UpdateTierContainers(state);
        UpdateXenoList(state.Xenos);
        UpdateStructureList(state.Structures);
    }

    #region State Updates

    private void UpdateButtonsState(MCXenoHiveStatusXenosBuiState state)
    {
        SetupButtonTexture(SkinsTexture, "/Textures/_RMC14/Actions/xeno_actions.rsi", "watch_xeno");

        SetupButtonTexture(BlessingsTexture, "/Textures/_MC/Interface/Actions/Xeno/queen.rsi", "blessing");
        BlessingsButton.Visible = !state.BlessingsHide;

        SetupButtonTexture(EvolveTexture, "/Textures/_MC/Interface/Actions/Xeno/legacy.rsi", "evolve");
        EvolveButton.Visible = !state.EvolutionHide;

        SetupButtonTexture(DevolveTexture, "/Textures/_MC/Interface/Actions/Xeno/legacy.rsi", "deevolve");
        DevolveButton.Visible = !state.DevolutionHide;
    }

    private void UpdateHeaderInfo(MCXenoHiveStatusXenosBuiState state)
    {
        BorrowedLarvaLabel.Text = $"{state.BurrowedLarva}";
        UpdatePsyPointsDisplay(state.Psypoints);

        EvolutionBlock.Visible = !state.EvolutionPointsHide;
        LarvaGenerationBlock.Visible = state.LarvaGeneration;

        TotalSistersLabel.Text = $"Total Living Sisters: {state.Xenos.Count}";
    }

    private void UpdateEvolution(MCXenoHiveStatusXenosBuiState state)
    {
        var evolutionNormalized = state.EvolutionPointsMax > 0
            ? double.Clamp((double)state.EvolutionPoints / state.EvolutionPointsMax, 0.0, 1.0)
            : 0.0;

        EvolutionProgressBar.Value = (float)evolutionNormalized * 100f;
        EvolutionProgressLabel.Text = $"{(int)double.Round(evolutionNormalized * 100)}%";
    }

    private void UpdateTierContainers(MCXenoHiveStatusXenosBuiState state)
    {
        TiersContainer.DisposeAllChildren();

        var isCompact = CompactModeCheckBox?.Pressed ?? false;
        var xenosByTier = state.Xenos
            .GroupBy(x => x.Tier)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var (tier, maxSlots) in state.TierSlots.OrderByDescending(kvp => kvp.Key))
        {
            var tierXenos = xenosByTier.GetValueOrDefault(tier, new List<MCXenoEntity>());
            if (tierXenos.Count == 0)
                continue;

            var tierPanel = CreateTierPanel(tier, maxSlots, tierXenos, isCompact);
            TiersContainer.AddChild(tierPanel);
        }
    }

    private void UpdateXenoList(List<MCXenoEntity> xenos)
    {
        XenoList.Children.Clear();

        foreach (var xeno in xenos.OrderBy(x => x.Name))
        {
            var row = CreateXenoRow(xeno);
            XenoList.AddChild(row);
        }
    }

    private void UpdateStructureList(List<MCXenoStructure> structures)
    {
        StructuresList.Children.Clear();

        if (structures.Count == 0)
        {
            StructuresList.AddChild(new Label
            {
                Text = "No active structures",
                Modulate = new Color(0.5f, 0.5f, 0.5f),
                Align = Label.AlignMode.Center,
            });
            return;
        }

        foreach (var structure in structures.OrderBy(s => s.Name))
        {
            var row = CreateStructureRow(structure);
            StructuresList.AddChild(row);
        }
    }

    #endregion

    #region UI Builders

    private void SetupButtonTexture(TextureRect texture, string rsiPath, string stateName)
    {
        var sprite = new SpriteSpecifier.Rsi(new ResPath(rsiPath), stateName);
        texture.Texture = _sprite.Frame0(sprite);
        texture.TextureScale = new Vector2(2f, 2f);
    }

    private PanelContainer CreateTierPanel(int tier, int maxSlots, List<MCXenoEntity> tierXenos, bool isCompact)
    {
        var castes = tierXenos
            .GroupBy(x => x.Id?.Id ?? x.Name)
            .OrderBy(g => g.Key)
            .Select(g => (CasteId: g.Key, Count: g.Count(), Entities: g.ToList()))
            .ToList();

        var tierPanel = new PanelContainer();
        var tierMainBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
        tierPanel.AddChild(tierMainBox);

        var headerText = maxSlots > 0
            ? $"Tier {tier}: ({tierXenos.Count}/{maxSlots}) Sisters"
            : $"Tier {tier}: {tierXenos.Count} Sisters";

        tierMainBox.AddChild(new Label
        {
            Text = headerText,
            Align = Label.AlignMode.Center,
            Margin = new Thickness(0, 0, 0, 4),
        });

        var castesBox = new BoxContainer
        {
            Orientation = isCompact ? BoxContainer.LayoutOrientation.Vertical : BoxContainer.LayoutOrientation.Horizontal,
            Align = isCompact ? BoxContainer.AlignMode.Begin : BoxContainer.AlignMode.Center
        };
        tierMainBox.AddChild(castesBox);

        foreach (var (casteId, count, entities) in castes)
        {
            castesBox.AddChild(CreateCasteRow(casteId, count, entities, isCompact));
        }

        return tierPanel;
    }

    private Control CreateCasteRow(string casteId, int count, List<MCXenoEntity> entities, bool isCompact)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4, 2),
            MinSize = new Vector2(60, 0),
        };

        var icon = GetCasteIcon(casteId);
        var name = GetCasteName(casteId) ?? casteId;

        var topRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        if (icon is not null)
            topRow.AddChild(icon);

        if (isCompact)
        {
            topRow.AddChild(new Label { Text = $"{count}" });
            row.AddChild(topRow);
            row.AddChild(new Label { Text = name, Align = Label.AlignMode.Left });
        }
        else
        {
            topRow.AddChild(new Label { Text = name });
            row.AddChild(topRow);
            row.AddChild(new Label
            {
                Text = $"{count}",
                Align = Label.AlignMode.Center,
                FontColorOverride = Color.Orange
            });
        }

        return row;
    }

    private BoxContainer CreateXenoRow(MCXenoEntity xeno)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(2, 1),
        };

        row.AddChild(new Label
        {
            Text = xeno.Name,
            HorizontalExpand = true,
            ClipText = true
        });

        row.AddChild(new Label
        {
            Text = FormatHealthText(xeno.Health),
            MinWidth = 50,
            HorizontalAlignment = HAlignment.Left,
            FontColorOverride = GetHealthColor(xeno.Health),
        });

        row.AddChild(new Label { Text = " | ", MinWidth = 20 });

        row.AddChild(new Label
        {
            Text = $"P: {(int)(xeno.Plasma * 100)}%",
            MinWidth = 45,
            HorizontalAlignment = HAlignment.Left,
            FontColorOverride = GetPlasmaColor(xeno.Plasma),
        });

        var watchButton = new Button
        {
            Text = "W",
            MinSize = new Vector2(24, 20),
            TextAlign = Label.AlignMode.Center,
            ToolTip = "Watch this xenomorph",
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(4, 0, 0, 0)
        };

        // Directly invoke the main event instead of using intermediate wrapper methods
        watchButton.OnPressed += _ => OnButtonWatch?.Invoke(xeno.Entity);

        row.AddChild(watchButton);
        return row;
    }

    private BoxContainer CreateStructureRow(MCXenoStructure structure)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(2, 1),
        };

        row.AddChild(new Label
        {
            Text = structure.Name,
            HorizontalExpand = true,
            ClipText = true,
        });

        row.AddChild(new Label
        {
            Text = FormatHealthText(structure.Health),
            MinWidth = 50,
            HorizontalAlignment = HAlignment.Right,
            FontColorOverride = GetHealthColor(structure.Health)
        });

        var watchButton = new Button
        {
            Text = "W",
            MinSize = new Vector2(24, 20),
            TextAlign = Label.AlignMode.Center,
            ToolTip = "Watch this structure",
            Margin = new Thickness(4, 0, 0, 0)
        };

        // Directly invoke the main event instead of using intermediate wrapper methods
        watchButton.OnPressed += _ => OnButtonWatch?.Invoke(structure.Entity);

        row.AddChild(watchButton);
        return row;
    }

    private void UpdatePsyPointsDisplay(Dictionary<ProtoId<MCXenoHivePsypointTypePrototype>, int> psypoints)
    {
        if (psypoints.Count == 0)
        {
            PsyPointsBlock.Visible = false;
            return;
        }

        PsyPointsBlock.Visible = true;
        PsyPointsContainer.DisposeAllChildren();

        foreach (var (protoId, value) in psypoints.OrderBy(kv => kv.Key))
        {
            if (!_prototype.TryIndex(protoId, out var proto))
                continue;

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            row.AddChild(new Label
            {
                Text = $"{Loc.GetString(proto.Name)}:",
                Modulate = new Color(0.85f, 0.85f, 0.85f)
            });

            row.AddChild(new Label
            {
                Text = $" {value}",
                Modulate = new Color(1f, 0.85f, 0.3f),
            });

            PsyPointsContainer.AddChild(row);
        }
    }

    #endregion

    #region Utilities

    private TextureRect? GetCasteIcon(EntProtoId id)
    {
        if (!_prototype.TryIndex(id, out var proto))
            return null;

        if (!proto.Components.TryGetComponent("TacticalMapIcon", out var comp) ||
            comp is not TacticalMapIconComponent tactical ||
            tactical.Icon is null)
        {
            return null;
        }

        return new TextureRect
        {
            Texture = _sprite.GetFrame(tactical.Icon, TimeSpan.Zero),
            Margin = new Thickness(0, 0, 4, 0),
            TextureScale = new Vector2(2, 2),
        };
    }

    private string? GetCasteName(EntProtoId id)
    {
        return _prototype.TryIndex(id, out var proto) ? proto.Name : null;
    }

    private static Color GetPlasmaColor(float plasma)
    {
        var r = MathHelper.Lerp(0.2f, 0f, plasma);
        var g = MathHelper.Lerp(0.2f, 1f, plasma);
        var b = MathHelper.Lerp(0.5f, 1f, plasma);
        return new Color(r, g, b);
    }

    private static string FormatHealthText(float health)
    {
        var percent = (int) float.Round(health * 100);
        return health < 0 ? $"[!] H: {percent}%" : $"H: {percent}%";
    }

    private static Color GetHealthColor(float health)
    {
        if (health >= 0f)
        {
            return health < 0.5f
                ? new Color(1f, health * 2f, 0f)
                : new Color(1f - (health - 0.5f) * 2f, 1f, 0f);
        }

        var severity = -health;
        const float r = 1.0f;
        var g = float.Lerp(0.6f, 0.27f, severity);
        var b = float.Lerp(0.0f, 0.27f, severity);

        if (severity <= 0.8f)
            return new Color(r, g, b);

        var boost = (severity - 0.8f) * 2.5f;
        return new Color(
            r,
            float.Clamp(g + boost * 0.15f, 0f, 1f),
            float.Clamp(b + boost * 0.15f, 0f, 1f)
        );
    }

    #endregion
}
