- type: entity
  abstract: true
  parent: BaseStorageItem
  id: MCPacketPills
  name: pill packet
  description: Contains pills. Once you take them out, they don't go back in.
  components:
  - type: Sprite
    sprite: _MC/Objects/Medical/packet_canister.rsi
    layers:
    - state: packet_canister
    - state: packet_canister1
      map: ["packet_canister1"]
      visible: false
      color: "#1461de"
    - state: packet_canister2
      map: ["packet_canister2"]
      visible: false
      color: "#1461de"
    - state: packet_canister3
      map: ["packet_canister3"]
      visible: false
      color: "#1461de"
    - state: packet_canister4
      map: ["packet_canister4"]
      visible: false
      color: "#1461de"
    - state: packet_canister5
      map: ["packet_canister5"]
      visible: false
      color: "#1461de"
    - state: packet_canister6
      map: ["packet_canister6"]
      visible: false
      color: "#1461de"
    - state: packet_canister7
      map: ["packet_canister7"]
      visible: false
      color: "#1461de"
    - state: packet_canister8
      map: ["packet_canister8"]
      visible: false
      color: "#1461de"
  - type: Item
    sprite: _MC/Objects/Medical/packet_canister.rsi
    size: Small
  - type: Storage
    hideStackVisualsWhenClosed: false
    maxItemSize: Small
    grid:
    - 0,0,15,1 # 8 slots
    whitelist:
      tags:
      - MCPill
  - type: RemoveOnlyStorage
  - type: FixedItemSizeStorage
  - type: Tag
    tags:
    - MCPacketPills
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno
  - type: ItemCounter
    count:
      tags:
      - MCPill
    composite: true
    layerStates:
    - packet_canister1
    - packet_canister2
    - packet_canister3
    - packet_canister4
    - packet_canister5
    - packet_canister6
    - packet_canister7
    - packet_canister8
  - type: Appearance

- type: Tag
  id: MCPacketPills
