- type: job
  parent: MCJob
  id: MCSpatialAgent
  name: mc-job-name-spatial-agent
  description: mc-job-description-spatial-agent
  playTimeTracker: MCSpatialAgent
  startingGear: MCGearSpatialAgentEquipped
  icon: MCSpatialAgent
  joinNotifyCrew: true
  supervisors: mc-job-supervisors-nanotrasen
  accessGroups: [ MCSpatialAgent ]
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        MCSkillEngineer: 4
        MCSkillConstruction: 4
        MCSkillMedical: 4
        MCSkillSurgery: 4
        MCSkillPolice: 4
        MCSkillPowerLoader: 4
        MCSkillLeadership: 4
        MCSkillSmartGun: 4
        MCSkillFirearms: 4
        MCSkillOverwatch: 4
        MCSkillCqc: 4
        MCSkillFireman: 4
        MCSkillEndurance: 4
        MCSkillJtac: 4
        MCSkillExecution: 4
        MCSkillIntel: 4
        MCSkillNavigations: 4
        MCSkillVehicles: 4
    - type: JobPrefix
      prefix: mc-job-prefix-spatial-agent

- type: playTimeTracker
  id: MCSpatialAgent
  isHumanoid: true

- type: startingGear
  id: MCGearSpatialAgentEquipped
  equipment:
    id: MCIDCardSpatialAgent
    shoes: MCLaceupSpatialAgent
    jumpsuit: MCJumpsuitSpatialAgent
    gloves: MCClothingHandsSpatialAgent
    ears: MCHeadsetSpatialAgent
    eyes: MCSunGlassesSpatialAgent
    back: MCSatchelMarineStandard
    belt: MCClothingBeltToolsFill
