using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Attachable.Components;
using Content.Shared._RMC14.Weapons.Ranged;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._MC.Guidebook.UI.Components;

/// <summary>
/// Control for embedding a weapon into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideWeaponEmbed : BoxContainer, IDocumentTag, ISearchableControl, IPrototypeRepresentationControl
{
    [Dependency] private readonly ILogManager _logManager = null!;
    [Dependency] private readonly IPrototypeManager _prototype = null!;
    [Dependency] private readonly IComponentFactory _componentFactory = null!;
    [Dependency] private readonly IEntityManager _entity = null!;

    public IPrototype? RepresentedPrototype { get; private set; }

    private readonly ISawmill _sawmill;

    private EntityUid? _iconEntity;

    public GuideWeaponEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("guidebook.weapon");

        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideWeaponEmbed(string weaponId) : this()
    {
        if (_prototype.TryIndex<EntityPrototype>(weaponId, out var weapon))
            GenerateControl(weapon);
    }

    public GuideWeaponEmbed(EntityPrototype weapon) : this()
    {
        GenerateControl(weapon);
    }

    protected override void Deparented()
    {
        if (_iconEntity is not null)
            _entity.DeleteEntity(_iconEntity.Value);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Weapon", out var id))
        {
            _sawmill.Error("Weapon embed tag is missing weapon prototype argument");
            return false;
        }

        if (!_prototype.TryIndex<EntityPrototype>(id, out var weapon))
        {
            _sawmill.Error("Specified weapon prototype \"" + id + "\" is not a valid entity prototype");
            return false;
        }

        GenerateControl(weapon);

        control = this;
        return true;
    }

    private void GenerateControl(EntityPrototype weapon)
    {
        RepresentedPrototype = weapon;

        if (_iconEntity != null)
            _entity.DeleteEntity(_iconEntity.Value);

        _iconEntity = _entity.SpawnEntity(weapon.ID, MapCoordinates.Nullspace);
        WeaponSprite.SetEntity(_iconEntity.Value);

        // Name and ID
        WeaponHeaderLabel.SetMarkup("[font size=12][color=#6a9a6a]ОРУЖИЕ[/color][/font]");
        WeaponName.SetMarkup($"[font size=24][bold]{weapon.Name}[/bold][/font]");
        WeaponId.SetMarkup($"[color=#6a9a6a]{weapon.ID}[/color]");
        WeaponDescription.SetMarkup(weapon.Description);

        GenerateStats(weapon);
        GenerateAmmo(weapon);
        ProcessAttachableHolderComponent(weapon);
        ProcessMeleeWeaponComponent(weapon);
    }

    private void GenerateStats(EntityPrototype weapon)
    {
        StatsRowsContainer.Children.Clear();
        StatsOuterContainer.Visible = false;

        var hasStats = false;

        if (weapon.TryGetComponent<RMCSelectiveFireComponent>(out var selectiveFire, _componentFactory))
        {
            AddStatRow(StatsRowsContainer, "Скорострельность (секунда)", $"{selectiveFire.BaseFireRate} выстр./сек");
            AddStatRow(StatsRowsContainer, "Скорострельность (минута)", $"{selectiveFire.BaseFireRate * 60} выстр./мин");
            AddStatRow(StatsRowsContainer, "Режимы огня", string.Join(", ", selectiveFire.BaseFireModes));
            //AddStatRow(StatsRowsContainer, "Бронепробитие оружия", $"{selectiveFire.ArmorPenetration}");
            AddStatRow(StatsRowsContainer, "Отдача · в упоре", $"{selectiveFire.RecoilWielded}");
            AddStatRow(StatsRowsContainer, "Отдача · с рук", $"{selectiveFire.RecoilUnwielded}");
            AddStatRow(StatsRowsContainer, "Разброс · в упоре", $"{selectiveFire.ScatterWielded * 180 / Math.PI:F2}°");
            AddStatRow(StatsRowsContainer, "Разброс · с рук", $"{selectiveFire.ScatterUnwielded * 180 / Math.PI:F2}°");
            hasStats = true;
        }

        if (weapon.TryGetComponent<GunComponent>(out var gun, _componentFactory) && gun.ShotsPerBurst > 0)
        {
            AddStatRow(StatsRowsContainer, "Очередь", $"{gun.ShotsPerBurst} выстр.");
            hasStats = true;
        }

        if (weapon.TryGetComponent<RMCWeaponAccuracyComponent>(out var accuracy, _componentFactory))
        {
            AddStatRow(StatsRowsContainer, "Точность · в упоре", $"x{accuracy.AccuracyMultiplier}");
            hasStats = true;
        }

        StatsOuterContainer.Visible = hasStats;
    }

    private void GenerateAmmo(EntityPrototype weapon)
    {
        AmmoRowsContainer.Children.Clear();
        AmmoOuterContainer.Visible = false;

        if (!weapon.TryGetComponent<ItemSlotsComponent>(out var itemSlots, _componentFactory))
            return;

        var slots = itemSlots.Slots;
        if (!slots.TryGetValue("gun_magazine", out var magSlot) || magSlot.StartingItem == null)
            return;

        if (!_prototype.TryIndex<EntityPrototype>(magSlot.StartingItem, out var magProto))
            return;

        AddStatRow(AmmoRowsContainer, "Магазин", magProto.Name);

        if (magProto.TryGetComponent<BallisticAmmoProviderComponent>(out var ballistic, _componentFactory))
        {
            AddStatRow(AmmoRowsContainer, "Ёмкость", $"{ballistic.Capacity} патронов");
        }

        AmmoOuterContainer.Visible = true;
    }

    private void ProcessAttachableHolderComponent(EntityPrototype weapon)
    {
        AttachmentsContainer.Children.Clear();
        AttachmentsOuterContainer.Visible = false;

        if (!weapon.TryGetComponent<AttachableHolderComponent>(out var attachableHolder, _componentFactory) ||
            attachableHolder.Slots.Count <= 0)
            return;

        foreach (var (slotId, slot) in attachableHolder.Slots)
        {
            var validTags = slot.Whitelist?.Tags;
            if (validTags is null || validTags.Count <= 0)
                continue;

            #region Readable slot

            // NO GOD HERE
            // ONLY FUCKING SANDBOX
            // CURSE OF 220

            // [ERRO] res.typecheck: Sandbox violation: Access to method not allowed: void [System.Runtime]System.ReadOnlySpan`1<char>..ctor(!0&)
            // [System.Runtime]System.ReadOnlySpan`1<char>..ctor in method Content.Client._MC.Guidebook.UI.Components.GuideWeaponEmbed.GenerateControl at IL 0x03A4

            // Normal version:
            /*
                var readableSlot =  slotId.Replace("mc-slot-", "").Replace("-", " ");
                if (readableSlot.Length > 0)
                    readableSlot = char.ToUpper(readableSlot[0]) + readableSlot[1..];
                */

            // Low-Level C# optimization
            /*
                string readableSlot = slotId.Replace("mc-slot-", "").Replace("-", " ");
                if (readableSlot.Length > 0)
                {
                    char upper = char.ToUpper(readableSlot[0]);
                    readableSlot = string.Concat(new ReadOnlySpan<char>(ref upper), string.op_Implicit(readableSlot.Substring(1)));
                }
                */

            // Robust toolbox hate me like hate fucking Span
            // Fuck

            var readableSlot =  slotId.Replace("mc-slot-", "").Replace("-", " ");
            if (readableSlot.Length > 0)
            {
                // 220 allocations per second
                var chars = readableSlot.ToCharArray();
                chars[0] = char.ToUpper(chars[0]);
                readableSlot = new string(chars);
            }

            #endregion

            var tagsText = string.Join(", ", validTags.Select(t => t.Id.Replace("MCAttachment", "")));

            AddStatRow(AttachmentsContainer, readableSlot, tagsText);
        }

        AttachmentsOuterContainer.Visible = true;
    }

    private void ProcessMeleeWeaponComponent(EntityPrototype weapon)
    {
        MeleeRowsContainer.Children.Clear();
        MeleeOuterContainer.Visible = false;

        if (!weapon.TryGetComponent<MeleeWeaponComponent>(out var melee, _componentFactory))
            return;

        var damage = melee.Damage;
        if (damage.DamageDict.Count <= 0)
            return;

        foreach (var (type, value) in damage.DamageDict)
        {
            AddStatRow(MeleeRowsContainer, type, value.ToString());
        }

        MeleeOuterContainer.Visible = true;
    }

    private void AddStatRow(BoxContainer container, string label, string value)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var labelControl = new RichTextLabel
        {
            HorizontalExpand = true
        };
        labelControl.SetMarkup($"[color=#888888]{label}[/color]");

        var valueControl = new RichTextLabel();
        valueControl.SetMarkup($"[bold]{value}[/bold]");

        row.AddChild(labelControl);
        row.AddChild(valueControl);
        container.AddChild(row);

        // Separator line
        var separator = new HLine
        {
            Color = Color.FromHex("#404040"),
            Thickness = 2,
            Margin = new Thickness(0, 5, 0, 5)
        };
        container.AddChild(separator);
    }
}
