using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Nuke.Generator.UI;

[GenerateTypedNameReferences]
public sealed partial class MCNukeDiskGeneratorWindow : DefaultWindow
{
    public MCNukeDiskGeneratorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
