- type: entity
  parent: BaseStructure
  id: MCWallInvincibleNoIcon
  abstract: True
  description: A huge chunk of metal used to separate rooms.
  categories: [ MCContent ]
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: CEZLevelHighGround
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Sprite
    drawdepth: Walls
  - type: PlacementReplacement
    key: walls
  - type: Occluder
  - type: Airtight
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - WallLayer
        density: 1000
  # - type: XenoWeedable
  #   spawn: XenoWeedsWall
  - type: XenoConstructionSupport
  - type: RMCDropshipBlocked
  - type: MinimapColor
    color: "#ebe5e5ee"
  - type: IsRoof
  - type: SunShadowCast
  - type: Tag
    tags:
    - Wall

- type: entity
  parent: MCWallInvincibleNoIcon
  id: MCWallInvincibleBase
  description: A huge chunk of metal used to separate rooms.
  abstract: true
  components:
  - type: Icon
    state: full
  - type: Tag
    tags: [ MCXenoIgnoreBanish ]

- type: entity
  parent: MCWallInvincibleNoIcon
  id: MCWall
  description: A huge chunk of metal used to separate rooms.
  abstract: true
  components:
  - type: Damageable
    damageContainer: StructuralMarine
    damageModifierSet: StructuralMarine
  - type: Corrodible
    isCorrodible: true
    structure: true
    meltTimeMult: 3
  - type: Clickable
  - type: RMCWallExplosionDeletable
  - type: DestroyedByExplosionType
  - type: DamageMultiplierFlags
    flags: Turf
  - type: ReceiverXenoClaws
    hitsToDestroy: 20
  - type: Appearance
  - type: Bullethole
  - type: RMCGenericExamine
    message: rmc-structure-wall-repair-examine-tip
    whitelist:
      components:
      - Marine
  - type: RMCRepairable
    heal: 200
    delay: 1
  - type: XenoToggleChargingDamage
    stop: true
    damage:
      types:
        MCBrute: 13
  - type: IconSmooth
    key: walls
    additionalKeys:
    - windows
    - doors

- type: examinableDamage
  id: MCGirderMessages
  messages:
  - rmc-girder-integrity-1
  - rmc-girder-integrity-2
  - rmc-girder-integrity-3
  - rmc-girder-integrity-4

- type: entity
  parent: BaseStructure
  id: MCGirder
  name: girder
  categories: [ MCContent ]
  components:
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,0.45"
        density: 60
        mask:
        - MachineMask
        layer:
        - GlassAirlockLayer
  - type: Clickable
  - type: InteractionOutline
  - type: StaticPrice
    price: 30
  - type: Sprite
    sprite: _RMC14/Structures/Walls/girder.rsi
    state: girder
  - type: Icon
    sprite: _RMC14/Structures/Walls/girder.rsi
    state: girder
  - type: Construction
    graph: MCGirder
    node: mcgirder
  - type: Damageable
    damageModifierSet: RMCGirder
  - type: Destructible
    thresholds:
    - trigger: !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          MCGirderDamaged:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
  - type: ReceiverXenoClaws
    maxHealth: 300
    minimumXenoTier: 1
  - type: RMCDropshipBlocked
  - type: DamageMultiplierFlags
    flags: Breaching
  - type: XenoToggleChargingDamage
    stageLoss: 4
    damage:
      types:
        MCBrute: 40
  - type: XenoCrusherChargable
  - type: RMCGenericExamine
    message: rmc-structure-girder-examine-tip
    whitelist:
      components:
      - Marine

- type: entity
  parent: MCGirder
  id: MCGirderReinforced
  name: reinforced girder
  components:
  - type: Sprite
    sprite: _RMC14/Structures/Walls/girder.rsi
    state: reinforced
  - type: Icon
    sprite: _RMC14/Structures/Walls/girder.rsi
    state: girder
  ##- type: Construction
  ##  graph: MCGirder
  ##  node: reinforcedGirder
  - type: Destructible
    thresholds:
    - trigger: !type:DamageTrigger
        damage: 500
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          MCGirderDamaged:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger: !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          MCGirderDamaged:
            min: 1
            max: 1
      - !type:SpawnEntitiesBehavior
        spawn:
          MCSheetMetal1:
            min: 1
            max: 1
          MCSheetPlasteel1:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
  - type: ReceiverXenoClaws
    maxHealth: 600
  - type: StaticPrice
    price: 66

- type: entity
  parent: MCGirder
  id: MCGirderDisplaced # TODO RMC14 : Requires crowbarring to be used as a girder
  name: displaced
  suffix: Girder
  components:
  - type: Transform
    anchored: false
  - type: Sprite
    state: displaced
  - type: Icon
    state: displaced

- type: entity
  id: MCGirderDamaged
  name: damaged girder
  description: A twisted girder that no longer blocks passage.
  categories: [ MCContent ]
  components:
  - type: Transform
    anchored: true
  - type: Clickable
  - type: Sprite
    sprite: _RMC14/Structures/Walls/structures.rsi
    state: girder_damaged
  - type: Icon
    sprite: _RMC14/Structures/Walls/structures.rsi
    state: girder_damaged
  - type: ExaminableDamage
    messages: MCGirderMessages
  - type: Damageable
    damageContainer: StructuralMarine
    damageModifierSet: StructuralMarine
  - type: Destructible
    thresholds:
    - trigger: !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          MCSheetMetal1:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Corrodible
    isCorrodible: true
    structure: true
  - type: ReceiverXenoClaws
    maxHealth: 100
  - type: RMCRepairable
    skill: MCSkillEngineer
    delay: 3
  - type: RMCRepairableReplace
    prototype: MCGirder
  - type: Construction
    graph: MCGirderDamaged
    node: mcgirderdamaged

  - type: RMCGenericExamine
    message: rmc-structure-displaced-examine-tip
    whitelist:
      components:
      - Marine
