using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Medical.Scanner;

[GenerateTypedNameReferences]
public sealed partial class MCHealthScannerWindow : DefaultWindow
{
    public MCHealthScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
