- type: entity
  parent: RMCHelmetBase
  id: MCArmorHelmetModularJaeger
  abstract: true
  components:
  - type: Sprite
  - type: Clothing
    clothingVisuals:
      head:
      - state: equipped-HELMET
      - state: visor
  - type: MCArmor
    soft:
      melee: 50
      bullet: 70
      laser: 70
      energy: 60
      bomb: 55
      bio: 55
      fire: 55
      acid: 60
  - type: HideLayerClothing
    slots:
    - Hair
    - HeadTop
    - HeadSide
    - Snout
  - type: IntegratedVisors
    visorsToAdd:
    - RMCVisorSquadIntegrated
  - type: RMCBulkyArmor
  - type: OverwatchCamera
  - type: MCArmorModularClothing
    slots:
    - id: main_helmet
      whitelist:
        tags:
        - MCArmorModuleHead
