- type: entity
  parent: RMCBaseMarineArmorLight
  id: MCArmor
  categories: [ MCContent ]
  abstract: true
  components:
  - type: MCArmorModularClothing
    slots:
    - id: main
      whitelist:
        tags:
          - MCArmorModuleBody
    - id: storage
      whitelist:
        tags:
          - MCArmorModuleBodyStorage
