- type: entity
  parent:
  # MC
  - MCArmorComponentLight
  - MCArmorComponentSounds
  - MCArmorComponentInteraction
  # RMC
  - ClothingOuterBaseMedium
  - MCAllowSuitStorageClothingArmor
  id: MCArmor
  categories: [ MCContent ]
  abstract: true
  components:
  - type: Item
    size: Huge
    heldPrefix: off
  # Visuals
  - type: Appearance
  - type: Sprite
    layers:
    - state: icon
    - sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/armor_overlays.rsi
      state: lamp-off
    - sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/armor_overlays.rsi
      state: lamp-on
      visible: false
      map: [ "light" ]
  # Clothing
  - type: Clothing
    equipDelay: 2
    unequipDelay: 2
    equipSound:
      path: /Audio/_RMC14/Machines/armor_equip.ogg
    equippedPrefix: off
    clothingVisuals:
      outerClothing:
      - state: equipped-OUTERCLOTHING
      - sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/armor_overlays.rsi
        state: lamp-off
  - type: ToggleableVisuals
    spriteLayer: light
    clothingVisuals:
      outerClothing:
      - sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/armor_overlays.rsi
        state: lamp-on
  - type: ItemTogglePointLight
  # Armor
  - type: MoveOrderArmor
  - type: RMCNameItemOnVend
    item: Armor
  - type: CMHardArmor
  - type: RMCBulkyArmor
  - type: RMCMagneticArmor
  - type: SquadArmor
    layer: Armor
    slot: OUTERCLOTHING
    rsi:
      sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/armor_overlays.rsi
      state: std-armor
    leaderRsi:
      sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/armor_overlays.rsi
      state: sql-armor
  # UI
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
      enum.UniformAccessoriesUi.Key:
        type: UniformAccessoryBui
  # Modular
  - type: DoAfter
  - type: MCArmorModularClothing
    slots:
    - id: main
      whitelist:
        tags:
          - MCArmorModuleBody
    - id: storage
      whitelist:
        tags:
          - MCArmorModuleBodyStorage
    - id: customization
      whitelist:
        tags:
          - MCArmorModuleCustomizationBody

# Components
- type: entity
  id: MCArmorComponentLight
  abstract: true
  components:
  - type: RMCSuitLight
  - type: PointLight
    enabled: false
    radius: 5
    offset: 0,-0.85
    rotation: 90
    softness: 5
    autoRot: true
    netsync: false
    color: "#FFFFFF"
    mask: /Textures/_RMC14/Effects/LightMasks/wide_ellipsis.png
  - type: PointLightRotation
    rotation: 90
  - type: HandheldLight
    addPrefix: true
    blinkingBehaviourId: blinking
    radiatingBehaviourId: radiating
    turnOffSound:
      path: /Audio/_RMC14/Handling/suitlight_crank.ogg
    turnOnSound:
      path: /Audio/_RMC14/Machines/suitlight_on.ogg
  - type: LightBehaviour
    behaviours:
    - !type:FadeBehaviour
      id: radiating
      interpolate: Linear
      maxDuration: 2.0
      startValue: 3.0
      endValue: 2.0
      isLooped: true
      property: Radius
      enabled: false
      reverseWhenFinished: true
    - !type:PulseBehaviour
      id: blinking
      interpolate: Nearest
      maxDuration: 1.0
      minValue: 0.1
      maxValue: 2.0
      isLooped: true
      property: Radius
      enabled: false
  - type: Battery
    maxCharge: 600
    startingCharge: 600
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 2

- type: entity
  id: MCArmorComponentSounds
  abstract: true
  components:
  - type: EmitSoundOnPickup
    sound:
      collection: RMCEquipArmor
      params:
        volume: -4
  - type: EmitSoundOnDrop
    sound:
      collection: RMCEquipArmor
      params:
        volume: -4
  - type: EmitSoundOnLand
    sound:
      collection: RMCEquipArmor
      params:
        volume: -4

- type: entity
  id: MCArmorComponentInteraction
  abstract: true
  components:
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno
  - type: ClothingRequireEquipped
    autoUnequip: true
    denyReason: rmc-armor-not-marine-jumpsuit
    whitelist:
      tags:
      - RMCUniformMarine
  - type: RMCDefibrillatorBlocked
    popup: cm-defib-take-off-armor
    showOnExamine: false
  - type: NoHandsInteractionBlocked
