using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Xeno.Structures.PheromoneTowers.UI;

[GenerateTypedNameReferences]
public sealed partial class MCXenoStructuresPheromoneTowerWindow : RadialMenu
{
    public MCXenoStructuresPheromoneTowerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
