- type: entity
  parent:
  - MCMachineVending
  - MCVendingSectionsArmor
  - MCVendingSectionsArmorModules
  - MCVendingSectionsArmorModulesStorage
  - MCVendingSectionsArmorModulesHelmet
  id: MCMachineVendingGhmme
  name: GHMME Automated Closet
  description: An automated closet hooked up to a colossal storage unit of standard-issue uniform and armor.
  abstract: true
  components:
  - type: Sprite
    sprite: _MC/Structures/Machines/vending.rsi
    layers:
    - state: marineuniform-off
      map: [ "enum.VendingMachineVisualLayers.Base" ]
    - state: marineuniform
      map: [ "enum.VendingMachineVisualLayers.BaseUnshaded" ]

# Bundles armor
- type: entity
  id: MCVendorBundleArmorJaegerLight
  name: jaeger light armor kit
  description: A set of light scout pattern jaeger armor, including an armor suit and helmet.
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _MC/Clothing/OuterClothing/Armor/Modular/MarkTwo/Scout/steel.rsi
    state: icon
  - type: CMVendorBundle
    bundle:
    - MCArmorModularJaegerScout
    - MCArmorHelmetModularJaegerScout

- type: entity
  id: MCVendorBundleArmorJaegerMedium
  name: jaeger medium armor kit
  description: A set of medium ranger pattern jaeger armor, including an armor suit and helmet.
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _MC/Clothing/OuterClothing/Armor/Modular/MarkTwo/Ranger/steel.rsi
    state: icon
  - type: CMVendorBundle
    bundle:
    - MCArmorModularJaegerRanger
    - MCArmorHelmetModularJaegerRanger

- type: entity
  id: MCVendorBundleArmorJaegerHeavy
  name: jaeger heavy armor kit
  description: A set of heavy assault pattern jaeger armor, including an armor suit and helmet.
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _MC/Clothing/OuterClothing/Armor/Modular/MarkTwo/Assault/steel.rsi
    state: icon
  - type: CMVendorBundle
    bundle:
    - MCArmorModularJaegerAssault
    - MCArmorHelmetModularJaegerAssault
