- type: entity
  parent: RMCSmoke
  id: MCSmokeDepricated
  suffix: MC
  components:
  - type: Sprite
    sprite: _RMC14/Effects/smoke.rsi
    state: smoke2
  - type: TimedDespawn
    lifetime: 15
  - type: Appearance
  - type: ActiveEdgeSpreader
  - type: EdgeSpreader
    id: MCSmokeAcid
  - type: EvenSmoke
    spawn: MCSmokeDepricated
    range: 3
  - type: DeleteOnExplosion

- type: edgeSpreader
  id: MCSmokeAcid
  updatesPerSecond: 2
