using Content.Client._RMC14;
using Content.Shared._MC.ASRS.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Buttons;

[GenerateTypedNameReferences]
public sealed partial class MCASRSCategoryButton : BoxContainer
{
    public MCASRSCategoryButton()
    {
        RobustXamlLoader.Load(this);
        Button.AddStyleClass(CMStyleClasses.CMLabelAlignLeft);
        Button.Label.AddStyleClass(CMStyleClasses.CMLabelAlignLeft);
    }

    public MCASRSCategoryButton(MCASRSCategory category, Action<MCASRSCategory> pressed) : this()
    {
        Button.Text = Loc.GetString(category.Name);
        Button.Disabled = category.Entries.Count == 0;
        Button.OnPressed += _ => pressed.Invoke(category);
    }
}
