using Content.Shared._MC.ASRS.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Buttons;

[GenerateTypedNameReferences]
public sealed partial class MCASRSOrderButton : BoxContainer
{
    private event Action<MCASRSEntry, int> CountChanged;

    private readonly MCASRSEntry _entry;

    private int _count;

    public MCASRSOrderButton()
    {
        RobustXamlLoader.Load(this);

        CountChanged = null!;
        _entry = null!;
    }

    public MCASRSOrderButton(MCASRSEntry entry, int count, Action<MCASRSEntry, int> countChanged, bool showIcons = false)
    {
        RobustXamlLoader.Load(this);

        var sprite = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        var localizationManager = IoCManager.Resolve<ILocalizationManager>();

        _entry = entry;
        _count = count;

        AddSingleButton.OnPressed += _ => AdjustCount(1);
        RemoveSingleButton.OnPressed += _ => AdjustCount(-1);

        CountChanged = countChanged;

        IconTextureRect.Visible = showIcons;

        if (entry.Icon is not null)
            IconTextureRect.Texture = sprite.Frame0(entry.Icon);

        var name = entry.Name;
        if (entry.Entities.Count > 0 && localizationManager.GetEntityData(entry.Entities[0]).Name is { } entityName)
            name ??= entityName;

        OrderNameLabel.SetMessage($"{Loc.GetString(name ?? "Unknown")} ({entry.Cost})");

        RefreshCount(invoke: false);
    }

    public void AdjustCount(int count)
    {
        _count = Math.Max(_count + count, 0);
        RefreshCount();
    }

    public void RefreshCount(bool invoke = true)
    {
        CountLabel.Text = _count == 0 ? string.Empty : _count.ToString();

        if (invoke)
            CountChanged.Invoke(_entry, _count);
    }
}
