using Content.Shared._MC.Engineering.Beacon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Beacon.UI;

[GenerateTypedNameReferences]
public sealed partial class MCBeaconChooseWindow : DefaultWindow
{
    public event Action<NetEntity, object?>? Selected;

    private NetEntity? _selected;
    private object? _payload;

    public MCBeaconChooseWindow()
    {
        RobustXamlLoader.Load(this);

        CancelButton.StyleClasses.Add("ButtonSquare");
        CancelButton.StyleClasses.Add("ButtonColorRed");
        SubmitButton.StyleClasses.Add("ButtonSquare");
        SubmitButton.StyleClasses.Add("ButtonColorGreen");

        SubmitButton.OnPressed += _ => OnSubmit();
        CancelButton.OnPressed += _ => Close();
    }

    protected override void Opened()
    {
        base.Opened();

        _selected = null;

        RefreshSelect();
    }

    public void Refresh(List<MCBeaconSystem.NetBeaconWithName> entries, object payload)
    {
        _payload = payload;

        Container.Children.Clear();
        foreach (var entry in entries)
        {
            Container.AddChild(new ChooseButton(entry, OnSelected));
        }
    }

    private void OnSelected(NetEntity entity, ChooseButton context)
    {
        _selected = entity;

        foreach (var child in Container.Children)
        {
            child.StyleClasses.Remove("ButtonColorGreen");
        }

        context.StyleClasses.Add("ButtonColorGreen");

        RefreshSelect();
    }

    private void OnSubmit()
    {
        if (!_selected.HasValue)
            return;

        Selected?.Invoke(_selected.Value, _payload);
        Close();
    }

    private void RefreshSelect()
    {
        SubmitButton.Disabled = !_selected.HasValue;
    }

    private sealed class ChooseButton : Button
    {
        public ChooseButton(MCBeaconSystem.NetBeaconWithName entry, Action<NetEntity, ChooseButton> callback)
        {
            StyleClasses.Add("ButtonSquare");

            Text = entry.Name;
            OnPressed += _ => callback(entry.Uid, this);
        }
    }
}
