using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Xeno.Abilities.Skin;

[GenerateTypedNameReferences]
public sealed partial class MCXenoSkinWindow : DefaultWindow
{
    public MCXenoSkinWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
