using Content.Shared._MC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Settings.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MCChatTab : Control
{
    public MCChatTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(MCConfigVars.ChatEmoji, ChatEmoji);
        Control.Initialize();
    }
}
