using Content.Shared._MC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Settings.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MCQoLTab : Control
{
    public MCQoLTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(MCConfigVars.QoLRunAlert, RunAlert);
        Control.Initialize();
    }
}
