using Content.Shared._MC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Settings.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MCUITab : Control
{
    public MCUITab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(MCConfigVars.UISlotControlClipping, SlotClipping);
        Control.AddOptionCheckBox(MCConfigVars.UIRadialSpawnAtMouse, RadialPosition);
        Control.Initialize();
    }
}
