using Content.Shared._MC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Settings.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MCZLevelsTab : Control
{
    public MCZLevelsTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionPercentSlider(MCConfigVars.ZLevelsOffset, ZLevelsOffset, 0f, 1f, 1f);
        Control.AddOptionCheckBox(MCConfigVars.ZLevelsPhysicsClientSimulation, ZLevelsPhysicsClientSimulation);
        Control.AddOptionSlider(MCConfigVars.ZLevelsPhysicsTickRate, ZLevelsPhysicsFrameRate, 5, 60);

        Control.Initialize();
    }
}
