- type: job
  parent: MCJob
  id: MCJobSquad
  abstract: true
  hasSquad: true

- type: entity
  parent: MarkerBase
  id: MCSpawnPointJob
  description: A TTMC job spawner. Used for roundstart and late joins.
  suffix: Job Spawn
  categories: [ MCContent ]
  abstract: true
  components:
  - type: SpawnPoint
    spawn_type: Job
  - type: Sprite
    sprite: _MC/Markers/jobs.rsi
