using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Shuttles.DropshiPicker.UI;

[GenerateTypedNameReferences]
public sealed partial class MCDropshipPickerWindow : DefaultWindow
{
    public MCDropshipPickerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
