- type: entity
  parent:
  - MCXenoUnactiveBase
  # - MCAIXenoSimple # - MCXenoComponentAI
  # RMC
  - CMXenoDeveloped
  - RMCXenoSpeechSounds
  - RMCXenoCommendationReceiver
  - RMCXenoMobCollision
  id: MCXenoMinion
  abstract: true
  components:
  - type: InputMover
  - type: MCASRSCost
    cost: 50
