using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Xeno.Construction.Blessings.UI;

[GenerateTypedNameReferences]
public sealed partial class MCXenoBlessingsWindow : DefaultWindow
{
    public MCXenoBlessingsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
