using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._MC.Xeno.Construction.Blessings.UI;

[GenerateTypedNameReferences]
public sealed partial class MCXenoBlessingsChoiceControl : Control
{
    public MCXenoBlessingsChoiceControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Set(string name, Texture? texture, bool disabled = false)
    {
        NameLabel.SetMessage(name);
        Texture.Texture = texture;
        Button.Disabled = disabled;
    }

    public void Set(FormattedMessage msg, Texture? texture)
    {
        NameLabel.SetMessage(msg);
        Texture.Texture = texture;
    }
}
