using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Weapons.AttackModeSelection.UI;

[GenerateTypedNameReferences]
public sealed partial class MCWeaponAttackModeSelectionMenu : RadialMenu
{
    public MCWeaponAttackModeSelectionMenu()
    {
        RobustXamlLoader.Load(this);
    }
}
