using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Shuttle.Console.UI;

[GenerateTypedNameReferences]
public sealed partial class MCShuttleConsoleWindow : DefaultWindow
{
    public MCShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
