- type: job
  parent: MCJobSquad
  id: MCSquadLeader
  name: mc-job-name-squad-leader
  description: mc-job-description-squad-leader
  playTimeTracker: MCSquadLeader
  startingGear: MCSquadLeader
  dummyStartingGear: MCSquadLeader
  icon: MCSquadLeader
  joinNotifyCrew: false
  supervisors: mc-job-supervisors-co
  ranks:
    MCSergeantFirstClass: []
    MCGunnerySergeant:
    - !type:RoleTimeRequirement
      role: MCSquadLeader
      time: 600 # 25 hours
    MCFirstSergeant:
    - !type:RoleTimeRequirement
      role: MCSquadLeader
      time: 6000 # 100 hours
    MCMasterGunnerySergeant:
    - !type:RoleTimeRequirement
      role: MCSquadLeader
      time: 18000 # 300 hours
    MCCommandSergeantMajor:
    - !type:RoleTimeRequirement
      role: MCSquadLeader
      time: 60000 # 1000 hours
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillLeadership: 1
        RMCSkillSmartGun: 0
        RMCSkillFirearms: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: mc-job-prefix-leader
    - type: TacticalMapIcon
      icon:
        sprite: _MC/Interface/squad_marine_icons.rsi
        state: leader

- type: playTimeTracker
  id: MCSquadLeader
  isHumanoid: true

- type: startingGear
  id: MCSquadLeader
  equipment:
    id: MCDogtagSquadLeader

- type: entity
  parent: MCSpawnPointJob
  id: MCSpawnPointSquadLeader
  name: squad leader spawn point
  components:
  - type: SpawnPoint
    job_id: MCSquadLeader
  - type: Sprite
    state: leader_spawn
