using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Shuttles.Tadpole.UI;

[GenerateTypedNameReferences]
public sealed partial class MCShuttleTadpoleWindow : DefaultWindow
{
    public MCShuttleTadpoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
