- type: entity
  parent: MCMeleeWeapon
  id: MCMeleeWeaponVali
  abstract: true
  components:
  - type: Tag
    tags: [ MCMeleeWeaponVali ]
  - type: Appearance
  - type: Sprite
    layers:
    - state: icon
    - state: icon-loaded
      color: "#008000"
      map: [ "enum.MCWeaponValiVisualLayers.Blade" ]
  - type: Item
    size: Large
  - type: Clothing
    quickEquip: false
    slots:
    - belt
    - back
    - suitstorage
  - type: MeleeWeapon
    angle: 0
    wideAnimationRotation: -135
    soundHit:
      path: /Audio/Weapons/bladeslice.ogg
  - type: MCWeaponVali
    reagentCapacity: 45
    reagentDefaultIcon:
      sprite: _MC/Interface/Actions/Weapons/vali.rsi
      state: empty_backgrounded
    reagentData:
      # Bicaridine
      MCBicaridine:
        icon:
          sprite: _MC/Interface/Actions/Weapons/vali.rsi
          state: bicaridine_backgrounded
        effects:
        - !type:MCWeaponReagentDamageMultipliedEffect
          multiplier: 0.6
        - !type:MCWeaponReagentAdjustBruteLossUserEffect
          amount: -10
      # Kelotane
      MCKelotane:
        icon:
          sprite: _MC/Interface/Actions/Weapons/vali.rsi
          state: kelotane_backgrounded
        effects:
        - !type:MCWeaponReagentDamageMultipliedEffect
          multiplier: 0.6
        - !type:MCWeaponReagentFireEffect
          stacks: 10
      # Tricordrazine
      MCTricordrazine:
        icon:
          sprite: _MC/Interface/Actions/Weapons/vali.rsi
          state: tricordrazine_backgrounded
        effects:
        - !type:MCWeaponReagentDamageMultipliedEffect
          multiplier: 0.6
        - !type:MCWeaponReagentSunderEffect
          amount: -6.5
      # Tramadol
      MCTramadol:
        icon:
          sprite: _MC/Interface/Actions/Weapons/vali.rsi
          state: tramadol_backgrounded
        effects:
        - !type:MCWeaponReagentDamageMultipliedEffect
          multiplier: 0.6
        - !type:MCWeaponReagentSlowdownEffect
          slowdownDuration: 1.5
      # Dexalin
      MCDexalin:
        icon:
          sprite: _MC/Interface/Actions/Weapons/vali.rsi
          state: dexalin_backgrounded
        effects:
        - !type:MCWeaponReagentDamageMultipliedEffect
          multiplier: 0.6
        - !type:MCWeaponReagentPlasmaEffect
          amount: 25
          multiplier: 0.2
  - type: UserInterface
    interfaces:
      enum.MCWeaponValiSelectReagentUi.Key:
        type: MCWeaponValiSelectedReagentBui

- type: Tag
  id: MCMeleeWeaponVali
