- type: entity
  parent: PillCanister
  id: MCPillCanister
  name: pill bottle
  description: It's an airtight container for storing medication.
  categories: [ MCContent ]
  components:
  - type: Tag
    tags:
    - MCPillCanister
    - MCIconLabelAllow
  - type: Sprite
    sprite: _RMC14/Objects/Chemistry/pill_canister.rsi
    layers:
    - state: pill_canister
      map: [ "bottleSurfaceLayer" ]
    - state: open
      map: [ "openLayer" ]
    - state: closed
      map: [ "closedLayer" ]
  - type: Storage
    quickInsert: true
    areaInsert: true
    areaInsertRadius: 1
    storageInsertSound: /Audio/Effects/pill_insert.ogg
    storageRemoveSound: /Audio/Effects/pill_remove.ogg
    grid:
    - 0,0,15,1 # 16
    storageOpenSound:
      collection: CMPillBottleOpen
    maxItemSize: Small
    whitelist:
      components:
      - Pill
      tags:
      - Dice
      - Paper
  - type: Item
    size: Small
    sprite: _RMC14/Objects/Chemistry/pill_canister.rsi
  - type: GenericVisualizer
    visuals:
      enum.RMCPillBottleVisuals.Color:
        bottleSurfaceLayer:
          Orange: { state: pill_canister }
          Blue: { state: pill_canister1 }
          Yellow: { state: pill_canister2 }
          LightPurple: { state: pill_canister3 }
          LightGrey: { state: pill_canister4 }
          White: { state: pill_canister5 }
          LightGreen: { state: pill_canister6 }
          Cyan: { state: pill_canister7 }
          Pink: { state: pill_canister8 }
          Aquamarine: { state: pill_canister9 }
          Grey: { state: pill_canister10 }
          Red: { state: pill_canister11 }
          Black: { state: pill_canister12 }
      enum.SharedBagOpenVisuals.BagState:
        openLayer:
          Open: { visible: true }
          Closed: { visible: false }
        closedLayer:
          Open: { visible: false }
          Closed: { visible: true }
  - type: Appearance
  - type: IconLabel
    textColor: White
    storedOffset: 3, 12
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: Clothing
    quickEquip: false
    slots: [ suitstorage ]
  - type: RMCStorageEjectHand
    state: Last
    canToggleStorage: false
    ejectWhenEmpty: true
    nestedWhitelist:
      tags:
      - RMCBeltMedical
  - type: RMCSmartFridgeInsertable
    category: Pills

- type: Tag
  id: MCPillCanister
