using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Weapons.Vali.UI;

[GenerateTypedNameReferences]
public sealed partial class MCWeaponValiSelectedReagentMenu : RadialMenu
{
    public MCWeaponValiSelectedReagentMenu()
    {
        RobustXamlLoader.Load(this);
    }
}
