using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Vending.UI;

[GenerateTypedNameReferences]
public sealed partial class MCVendorQuickEquip : DefaultWindow
{
    public MCVendorQuickEquip()
    {
        RobustXamlLoader.Load(this);
    }
}
