- type: guideEntry
  parent: MC
  id: MCGuideXenoCastesTier1
  priority: 1
  text: "/ServerInfo/Guidebook/_MC/Guides/Xeno/MCGuideXenoCastes.xml"
  name: Тир 1

- type: guideEntry
  parent: MC
  id: MCGuideXenoCastesTier2
  priority: 2
  text: "/ServerInfo/Guidebook/_MC/Guides/Xeno/MCGuideXenoCastes.xml"
  name: Тир 2

- type: guideEntry
  parent: MC
  id: MCGuideXenoCastesTier3
  priority: 3
  text: "/ServerInfo/Guidebook/_MC/Guides/Xeno/MCGuideXenoCastes.xml"
  name: Тир 3
  children:
  - MCGuideXenoCrusher
  - MCGuideXenoDefiler
  - MCGuideXenoRavager
  - MCGuideXenoPraetorian