- type: entity
  parent: MCClothing
  id: MCOuterClothing
  abstract: true
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Pouches/small_drop.rsi
    state: icon
  - type: Appearance
  - type: Item
    size: Huge
  - type: Clothing
    quickEquip: true
    slots:
    - outerClothing
  - type: ExplosionResistance
    damageCoefficient: 0
    worn: false
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno

- type: entity
  abstract: true
  id: MCAllowSuitStorageClothingArmor
  components:
  - type: AllowSuitStorage
    whitelist:
      components:
      - RMCLighter
      - Bible
      - Gun
      - CassettePlayer
      tags:
      - GasTank
      - Flashlight
      - DiscreteHealthAnalyzer
      - CigPack
      - Knife
      - RMCG8Pouch
      - RMCMacheteScabbard
      - RMCScabbardKatana
      - MCScabbardKatana
      - MCScabbardMachete
      #TODO Various holsters should fit here - 47 belt, 1984, m44, and flaregun
      - RMCM82FHolster
      - RMCSmartPistolHolster
      - RMCSMGHolster
      - RMCSMGPouchHolster
      - RMCGeneralPistolHolster
      - RMCGeneralRevolverHolster
      - RMCBeltHolsterM13
      - RMCXM51Holster
      - RMCDetector
      - RMCMatebaHolster
