using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.CommunicationsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class MCCommunicationsConsoleWindow : DefaultWindow
{
    public MCCommunicationsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
