using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.Ui;

[GenerateTypedNameReferences]
public sealed partial class MCASRSCategoryView : Control
{
    public MCASRSCategoryView()
    {
        RobustXamlLoader.Load(this);
    }
}
