using Content.Shared._MC.ASRS.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.Ui;

[GenerateTypedNameReferences]
public sealed partial class MCASRSOrderButton : BoxContainer
{
    public event Action<int>? OnCountChanged;

    private int Count { get; set; }

    public MCASRSOrderButton()
    {
        RobustXamlLoader.Load(this);

        RemoveSingleButton.OnPressed += _ => AdjustCount(-1);
        AddSingleButton.OnPressed += _ => AdjustCount(1);
    }

    public void SetLabel(MCASRSEntry entry)
    {
        OrderNameLabel.SetMessage($"{entry.Name ?? "Unknown"} ({entry.Cost})");
    }

    public void AdjustCount(int count)
    {
        SetCount(Count + count);
    }

    public void SetCount(int count)
    {
        Count = Math.Max(count, 0);
        CountLabel.Text = Count == 0 ? string.Empty : Count.ToString();
        OnCountChanged?.Invoke(Count);
    }
}
