using System.Linq;
using Content.Client._MC.ASRS.UI.Views;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI;

[GenerateTypedNameReferences]
public sealed partial class MCASRSWindow : DefaultWindow
{
    public MCASRSWindow()
    {
        RobustXamlLoader.Load(this);

        HideAllViews();
    }

    [PublicAPI]
    public void OpenView(MCASRSBui bui, MCASRSView view)
    {
        HideAllViews();

        view.Visible = true;
        view.Open(bui);
    }

    [PublicAPI]
    public void HideAllViews()
    {
        foreach (var child in MainContainer.Children.Where(child => child is not MCASRSCategoryView))
        {
            child.Visible = false;
        }
    }
}
