using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.Ui;

[GenerateTypedNameReferences]
public sealed partial class MCASRSWindow : DefaultWindow
{
    public MCASRSWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
