using Content.Client._RMC14;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.Ui;

[GenerateTypedNameReferences]
public sealed partial class MCASRSCategoryButton : BoxContainer
{
    public MCASRSCategoryButton()
    {
        RobustXamlLoader.Load(this);

        Button.AddStyleClass(CMStyleClasses.CMLabelAlignLeft);
        Button.Label.AddStyleClass(CMStyleClasses.CMLabelAlignLeft);
    }

    public void SetName(string name)
    {
        Button.Text = name;
    }
}
