using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Settings;

[GenerateTypedNameReferences]
public sealed partial class MCSettingsMenu : DefaultWindow
{
    public MCSettingsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("mc-ui-options-tab-ui"));
        Tabs.SetTabTitle(1, Loc.GetString("mc-ui-options-tab-chat"));
        Tabs.SetTabTitle(2, Loc.GetString("mc-ui-options-tab-qol"));
        Tabs.SetTabTitle(3, Loc.GetString("mc-ui-options-tab-zlevels"));

        UpdateTabs();
    }

    public void UpdateTabs()
    {
        MCUI.Control.ReloadValues();
        MCChat.Control.ReloadValues();
        MCQol.Control.ReloadValues();
        MCZLevels.Control.ReloadValues();
    }
}
